# Generated by Django 5.0.3 on 2024-04-09 19:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('cards', wagtail.blocks.StructBlock([('section_title', wagtail.blocks.CharBlock(help_text='Title of the section', required=True)), ('section_description', wagtail.blocks.TextBlock(help_text='Description of the section', required=True)), ('section_button', wagtail.blocks.PageChooserBlock(help_text='Link to internal page', required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(help_text='Icon Image', required=True)), ('card_title', wagtail.blocks.CharBlock(help_text='Title of the card', required=True)), ('card_description', wagtail.blocks.TextBlock(help_text='Description of the card', required=True)), ('button_page', wagtail.blocks.PageChooserBlock(help_text='Link to internal page', required=False)), ('button_url', wagtail.blocks.URLBlock(help_text='Link to a external URL', required=False))])))])), ('about_us_blocks', wagtail.blocks.StructBlock([('block_title', wagtail.blocks.CharBlock(help_text='Title of the section', required=True)), ('block_description', wagtail.blocks.TextBlock(help_text='Description of the section', required=True)), ('about_title', wagtail.blocks.CharBlock(help_text='Title of the about us section', required=True)), ('about_description', wagtail.blocks.RichTextBlock(help_text='Description of the about us section', required=True)), ('button_page', wagtail.blocks.PageChooserBlock(help_text='Link to internal page', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image of the section', required=True))])), ('market_overview_blocks', wagtail.blocks.StructBlock([('block_title', wagtail.blocks.CharBlock(help_text='Title of the section', required=True)), ('button_page', wagtail.blocks.PageChooserBlock(help_text='Link to internal page', required=False))])), ('feed_block', wagtail.blocks.StructBlock([('block_title', wagtail.blocks.CharBlock(help_text='Title of the section', required=True)), ('feed_url', wagtail.blocks.CharBlock(help_text='Enter the URL of the RSS feed you want to display', required=True)), ('count', wagtail.blocks.CharBlock(help_text='Enter the number of items you want to display', required=True))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MarketOverview',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageCarouselImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', wagtail.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Title | Title must be included in H1 tag')),
                ('description', models.TextField(blank=True, null=True)),
                ('carousel_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
