# Generated by Django 5.0.3 on 2024-03-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_carouselitemsorderable_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
