# Generated by Django 5.0.3 on 2024-05-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
