# Generated by Django 5.0.3 on 2024-03-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepagecarouselimages_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='bodytext',
        ),
        migrations.AddField(
            model_name='header',
            name='about_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='home_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='login_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='logo_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='services_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='team_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='why_us_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
