# Generated by Django 5.0.3 on 2024-05-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_documents'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='document',
        ),
        migrations.AddField(
            model_name='documents',
            name='documents',
            field=models.ManyToManyField(blank=True, to='wagtaildocs.document'),
        ),
    ]
