# Generated by Django 5.0.3 on 2024-03-22 09:36

import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_header_bodytext_header_about_link_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('cards', wagtail.blocks.StructBlock([('section_title', wagtail.blocks.CharBlock(help_text='Title of the section', required=True)), ('section_description', wagtail.blocks.TextBlock(help_text='Description of the section', required=True)), ('section_button', wagtail.blocks.PageChooserBlock(help_text='Link to internal page', required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(help_text='Icon Image', required=True)), ('card_title', wagtail.blocks.CharBlock(help_text='Title of the card', required=True)), ('card_description', wagtail.blocks.TextBlock(help_text='Description of the card', required=True)), ('button_page', wagtail.blocks.PageChooserBlock(help_text='Link to internal page', required=False)), ('button_url', wagtail.blocks.URLBlock(help_text='Link to a external URL', required=False))])))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='rtfbody',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rtfblock', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('cards', wagtail.blocks.StructBlock([('section_title', wagtail.blocks.CharBlock(help_text='Title of the section', required=True)), ('section_description', wagtail.blocks.TextBlock(help_text='Description of the section', required=True)), ('section_button', wagtail.blocks.PageChooserBlock(help_text='Link to internal page', required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(help_text='Icon Image', required=True)), ('card_title', wagtail.blocks.CharBlock(help_text='Title of the card', required=True)), ('card_description', wagtail.blocks.TextBlock(help_text='Description of the card', required=True)), ('button_page', wagtail.blocks.PageChooserBlock(help_text='Link to internal page', required=False)), ('button_url', wagtail.blocks.URLBlock(help_text='Link to a external URL', required=False))])))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
