# Generated by Django 5.0.3 on 2024-03-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ourservices_delete_header_remove_homepage_rtfbody_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservices',
            name='body',
        ),
    ]
