# Generated by Django 5.0.3 on 2024-05-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_documents_document_documents_documents'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='documents',
        ),
        migrations.AddField(
            model_name='documents',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
    ]
