# Generated by Django 5.0.3 on 2024-05-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_document_alter_documents_document'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
